# Generated by Django 5.1.6 on 2025-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="AreasTecnologicas",
            fields=[
                (
                    "id_area_tecnologica",
                    models.AutoField(primary_key=True, serialize=False),
                ),
                ("area_tecnologia", models.CharField(max_length=100)),
            ],
        ),
    ]
