# Generated by Django 5.1.6 on 2025-03-05 12:44

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("areastecnologicas", "0001_initial"),
        ("colaboradores", "0001_initial"),
        ("financiadores", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Projeto",
            fields=[
                ("id_projeto", models.AutoField(primary_key=True, serialize=False)),
                ("projeto", models.CharField(max_length=100)),
                ("coordenador", models.CharField(max_length=100)),
                ("ativo", models.CharField(max_length=1)),
                ("inicio_vigencia", models.DateField()),
                ("fim_vigencia", models.DateField()),
                ("valor", models.DecimalField(decimal_places=2, max_digits=10)),
                ("qnt_membros", models.IntegerField()),
                (
                    "equipe",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="colaboradores.colaborador",
                    ),
                ),
                (
                    "id_area_tecnologica",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="areastecnologicas.areastecnologicas",
                    ),
                ),
                (
                    "id_finandicador",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="financiadores.financiador",
                    ),
                ),
            ],
        ),
    ]
