# Generated by Django 3.2.12 on 2025-03-06 21:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projeto', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projeto',
            old_name='id_finandicador',
            new_name='id_financiador',
        ),
    ]
