# Generated by Django 5.1.6 on 2025-03-05 12:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Financiador",
            fields=[
                ("id_financiador", models.AutoField(primary_key=True, serialize=False)),
                ("financiador", models.CharField(max_length=100)),
            ],
        ),
    ]
